### PR TITLE
Foundation of Rust gem extension

### PR DESCRIPTION
**Pull request by stevegeek**
Was planning to open this as a PR in case it could act as a useful starting point for any future Rust extension, but totally forgot... so opening it now. 

Feel free to close if not useful to the effort!

Thanks for the work on `tailwind_merge`!

### CODE REVIEW

**Comment by gjtorikian** [comment]
Hi, thanks for this. I think my first question would be to assess whether a Rust port would be beneficial, or how it would be so. Mainly there are two parts of the gem (determining how classes should merge, and then actually doing the merge) which could be Rustified. But I am curious if you have any real world benchmarks or examples of classes to merge (so that I can write the benchmarks) in order to better determine which part should have its performance improved  first.

**Comment by stevegeek** [comment]
Sure, will pull together some profiles from view rendering on our app. Our Rails app uses view components (and my gem Vident which can use  tailwind_merge to dedupe class lists). Using tailwind_merge instead of the original simple implementation of a dedupe of class names resulted in our production apps performance being affected and I had to rollback. On profiling investigation I saw the majority of page render time ended up in tailwind_merge hence my desire to create an optimised version. I seem to remember also noticing GC churn was an issue too.

Thanks for considering it!

**Comment by gjtorikian** [comment]
> On profiling investigation I saw the majority of page render time ended up in tailwind_merge hence my desire to create an optimised version. 

This is super interesting to me! It’s essentially what I was asking. Can you share any of those numbers? I want to optimize this, but in the right places you know?

**Comment by stevegeek** [comment]
@gjtorikian Hey! so I tried to dive deeper into this and couldn't replicate my previous concerns. I think what might have happened is I was accidentally creating a new `Merger` on each component render and this was what the problem was. At the time I also saw a large amount of Strings being created and hence GC churn and assumed they where also from tailwind_merge but actually on a deeper dive I think they are not connected or just related to initialising too many Mergers!. Sorry for the false flag here!

**Pull request closed without merging**
